# Site settings
title: Nicole Thompson 
email: nicolet5@uw.edu
description: > # this means to ignore newlines until "baseurl:"
  It's all about me 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
github_username:  nicolet5

# Build settings
markdown: kramdown
